# -- tmux configuration --

# True color support 
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*256col*:Tc"

# Enable undercurl and underscore colors 
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g prefix C-a
set -g mouse on
set -g renumber-windows on
set -g mode-keys vi
set -g focus-events on
set -s copy-command 'wl-copy'
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection
bind -T copy-mode-vi r send-keys -X rectangle-toggle

# Floats
bind g popup -E -w 80% -h 80% -d "#{session_path}" -b single -S fg=colour8 -T "#[fg=colour7]lazygit" "lazygit" # Lazygit
bind b popup -E -w 80% -h 80% -d "#{session_path}" -b single -S fg=colour8 -T "#[fg=colour7]posix" "sh" # Open a POSIX shell in a float

# Split panes using "\" and "-".
unbind %
bind-key "-" split-window -v
unbind '"'
bind-key "\\" split-window -h

# Resize panes with prefix-HJKL.
bind -r -T prefix J resize-pane -D 5
bind -r -T prefix K resize-pane -U 5
bind -r -T prefix H resize-pane -L 5
bind -r -T prefix L resize-pane -R 5
# Select panes with prefix-hjkl.

bind -T prefix j select-pane -D
bind -T prefix k select-pane -U
bind -T prefix h select-pane -L
bind -T prefix l select-pane -R

set -g pane-border-style 'fg=colour8'
set -g pane-active-border-style 'fg=colour8'
set -g status-position bottom 
set -g status-justify absolute-centre 
set -g status-style 'bg=colour0'
set -g status-right '#[bold fg=colour15]#S'
set -g status-left 'tmux'
set -g window-status-style 'fg=colour8'
set -g window-status-current-style 'fg=colour15 bold'
set -g window-status-last-style 'italics'
set -g window-status-format '#I:#W'
set -g window-status-current-format '#I:#W'
set -g window-status-separator ' '
